---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBomzpLXAWjb2Qx+Kqx888R9DjJxGCBoxa4atQ1O5DbZM4GTMTWA11IT/rQ6l199QN3455pK/gjiTobrNkEYZ6eJBna32vJUSoZskfhBG06d49k3jqBj29z0/PJKMe6tcSNM6Pi82/MYFPzXw/RDoLLI0MiUKQwa6cVx2QApwwzneb4g1wa8Miizalh3q/8rcMvV9qsZLiqluZlbew+C1v62ihU01xOILnSimpOaoX++KoxRryK1N9EK+5tSAvmHSIzLGOpILzGvgTmf55wgHry4ZAA/Y7JpFms4CJRfan1NosgbHEU+1pdetz/oNr7vtaPRf53eIkEtB6nfWcAUzwXphyG73SDQ9Wzw7jnA9gUZAEORQOhej659dSOgGRuMDiIOJCIBZqs+uKcJpGD30DH5pZbSeT60zPEqgUUDa8VWi/57XSTu32sdlMbTcn6RBal9VGPSWrwV0ricJl7ytQgX7CPV1HUsYXooTp8wZKGQXV9KnegG/FnyPBzjGfmE6m0WNtBJ2gjrHVnMNTNBFZvbgADfyigxF+WstG1BNt48zUW09KpA0A9NB/iT/dD9tLq2nJNSO3Y1u3hil3y/atG9YRGT6DUeCMzUTqalnNr9NTx/U4a1ATLWA9p7XMad1ln3Il0nsfgGt4oWp9k7JCNAKRyfnyO1G/c9kqmWcw1sgczRh7MBB5ZyV9FKhZZFHW+50Mz7Q==
    admin-user: AgADm0xsMXpBFfFOk9n0DMtdimw9C/tnzXVL80x7/SW3UmJmF9lZqPlvitVktVLKPO+mm2cIC0UE3rDxP0isLwXBJGA3BMAbsY/ZuOVfadCoH034Iol2PLn3gYx6uovvOpI0QylNDCC4LLuvpdRTyJpG9l51yI4Wzsx7/IZH7MGvCQ3re3tkkjXPeE9S3UYuNkGWkoAj2PL0VB7U+PUPDRTUEh76jtZwKcLaymy8xVL85rMDuqlL6xbKg0cNq7uh5E5bYJps/ESj8mkt3yrjMBBNQx1Fa7/ebaNEK5Ei7CvAQURC2/Ujt0CVgDZ4Kk+0xd/CoNpocyjN+zsPwjYcyK/XdOC24ex9irv1ZqgeMAxR4AJg++umLjhuh996/AW2SpcezABOpUf3BMBgbIipX0c45UnDv08eq8W8WXwZi9YPRCVVhifXGl71aEV47GRrOLm+ovd0XkXIiPBd4/Jc4teVJJtCYOavaLDVd4KkRPuectaN9zoy0+hrQ8fIG9hi+ue1166hK0c8bEQnvorcqMWsUXwCFp6BPrDL2rH0SgFvjkEHCfVmUIsGXN6T0jzXTGkLod8AWWkbSS1y2oixyww/WTh3PbpM+tSe6KaAd2fUX2VcyFFbUq2yjIkHMQqIR6Eey2KmT2fjw920SJqgwfbPwR690h5kp9fI23fjM/o35pVDIPLXOY27eySEmzn9d8FgKaFBWQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
