---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-auth
  namespace: mi-namespace
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgCW0uZ2EBCt8Iey7zWP6tGbtTyvaZFvzar2ybHJvXVn0O3S3fo5r6lnfZu8L0IhlAevT4/u+KuTbE3MJi1TcoxTyRg+f5bt6Brf7Oc8MTMDaJxcSBuYl0z8HY4JSOfETg/G1udDphR/U+El7vKM91nuFaszFCawQE5AprYUfWDgvhgzXHVA+vCCANBB+Tu3PXv0nSfSClPfHuI5SLtv2HKdAy7YgoWKR4eaiLS3LO/mg6l12oh2oZOUlLVNxB3ojVW+NS41dQfgwhNS+PTnI2a8io3Ml+9RGBADig+iK81c7p/Y8TlnuS6tASa2Hsqo4QpUfVYdPv92YDhXtGAHWy66IFuVPW6Uc/jKRcqV3ZyLLNhuAAmoldN7v97wlqhL6TIeqpAuL3OJ5ZFjolGwuLr1TJFRUndb1qmMgF1tQJqB+6IVeK/H+dQvMb4flbgRoK2V30OSXtEt43NMFSPxP1MWY2lsi1vMmRAE/jjdn+yA7n9c6wwK3F4BWV49d13UjC3NAL9/2TkUWC5UruztON6wE0XKWrOBbtyIw53JG4Oy9vh9YrhvKFnzcTi9Ed9FsImphlkcQFcMKmTesYeV/8tobsrbb0nclBOh11WpBH+0JZY5Kz9Dg+cqTLSDMMhEi/CGsFQsWoBastyCwFcrO5hHmPnTFW7uFcJQaF3z/CrWIVLA0aDgzh9Ts6E31tdmeRlCuHkQNXS15/FlGwiBJ1vAl4R+
    PGADMIN_DEFAULT_PASSWORD: AgAvxLNIPjjOHuWD0TLYn6mAQHP2mwPByibCsNnISRBuOoWJsL3W24dYRWnN/YjcAS676xkqkhw9+cu6s16Eg4efc1y4VPUNW2E2J+x72nnmy6xVzSgxl0pxAKqvl+q54aGxRqQ01QDzvFkTzWDYF93/OI25QwWO4L6WT7H9/SLEHW6HJEg4H2Nuf6ShoGz5nFTA7NYNPRWe19q7yr1SnQ6B3PRknThRLikDPoxChOy78Pf+XHzVpxz0Anl2okF1SX3B1J8q3yMhOAcGOImTWZALcAIQE4n/0jjtxzJtUHQU3FXztdZ/xL3E5SzSR9U5PlgLfFwe5ykwv7aH5dZ6W1rLSpp89vSdFpZLcE6Q6mpDlAlcrtV2KzwhHz+j/OKdcIFiQQKJMfdgXzcbKvW7EDgxjV50QFgo+hgn2LEj6U6+7T9Eog7PtIevo9pnzyUlBlDqXsWSrpHt77zK82Hi0GhC6HiefhU7M6SkSKqnVu7EBrs2USCZGpANxjnCkch4yGHY3t23O/3YORYRmTWd29nW6y54lZoJ2zJitfH4d7r8r5z34qoYVL3YNn/EO4hoE7vbHch+C+PaQLSzfLuArO9+iA7ls8l9lnZ0vlLzg3qAwU953x5HKaeOnT/SOCyVaU1bh1ZFJWiaeJLpTlCM4+VhKwjl8yLZa6/MrlXSgpLNIeBTJesYvEDrE3tjVqRXK8OgGYkNR1nmYg==
  template:
    metadata:
      name: pgadmin-auth
      namespace: default
