---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-auth
  namespace: default
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgBvY5oxUysKZ0fBuqTeRtsoEpGOkO7e1Wbni7+O0/srdPis2WFZrPFBGD8/jRzqolssHUjl3xJOcXn4KsQ1CG15yeYjwLAvyukCDOZtc/ClIdRpJfPIWE5DLrPapzLwAg+XEKv2rCINGlhvJGXu1HgM8nYm5IP/rwkWtFNIT4H7sMay+p5AO6Lyn7WQeioek1XdH+5T8tKoCS/Ye9LQXDuyHDpkVwGE1mA92DUhAhiwFMPPRi1C9OX2cim/tY12bnm+58SnnFZKwN1kkF0FwfTyLVTsT67FpX+mcLnY8Rnq9Cecg01BvuleUoM7Vr/so99wej7ejgONYtcNAztqONx8yYjEdRWhS3b3/aCOj3quHmXbQ9JrSyXpvhdStMGMkmop4Bd4Y4lE+OLKdppwO+g056dnBdYhjoJgZ6d7B/Pu+2PzMAtMw2SlZKTAUcpvLm9cz9ZQRLoRF3U7ddw/6vYmfhJunkEAoVHmLi4Ju2067BS0C/5xmns9KnsirV6JfyyfrUfFAzSdUVD4X4CxS/DAdBN0Dfc2O01+JugYDSvXU0rU3mkJFsrfpkGX83EXqJcZhumysWg4MeJQ9xMcw12mEy1xXKdPRxuaelJ5Bc/yNg4GXMFB1oibjVb3iQ3LSkTAHJoUBOB5nQ9fEA5t/skx0XKjkgzuN1OqMh9Pr4eQk2momcLpbM/ZARa6goHiyvUb0jeJngDr6phrlKjYSroLJz8=
    PGADMIN_DEFAULT_PASSWORD: AgBDRBQCpY+hqDxCui7Mx8n+1r1d0WqldywCjAyosF44hYJQPVLAjZQ4PcAU5yKFpsRL68qGbA8GsC5kPusq8gHVIJwFMQ1kmlxrtZYfGy0+3snoYj5FBUzZjOYvERj8WN0dFBnYQyGJLnGK5QOp6fvaqr+NRii7+qwaBYSGDYQX528ULfF36ne+5BS/mSgcxCo5wM7aP4hkLx+VyPh32dJuA3VpxOdpPRT2v8KgENfrycgV1dWPMTly3aVEKUHLj+umwTimszYM4X4sWfi1pbIqr0lZAY0Ev3fxxj3FIyI3rRbbiXz+TVszcX+GbnPdB0nBjuxOTq7uwyAqLrJZrN/moNOyFpBE3LbfaXIaQckza9xWHN0ogiEaLZnTJk/aX8N+0MKidRCSotWjXgUk4KbF7YZixp7Zzcjzw+jrAWBxXpDHgX+AkRJGNaahtK1CCQymffJa4Op8eVV6lcQ8YN/CdH/tg2asI4sY3W8VdHnFL4WvZhSx3xN6ldyebgpCpc2QNMZSKKs+hdCfT6PyiA4rVGYu3j7dP7+b8fFTb+tUCPfXP5Om8poJpdTngkgyrH8vd4LUt8TI+3jx1tZmLIkEd2uQalk9VqlYHx8na5S/yCjrbLraVO3TDw8r+56J4A5kREIaJzYOrGQh0yphZrhxlZKPCdTYWngEdswQ/q7nwc/l8kY5VngySFBNvpWXogGT5sSl4XT+pw==
  template:
    metadata:
      name: pgadmin-auth
      namespace: default
