---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-auth
  namespace: default
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgC4sr29jpkeNmgkupZcjVoATaB3g+7lFCowVoRPskapvZZpYJ3PsanJJo1ve4vgi4K6S7HBFbR8Oa2Kh0CC27mbWr//5VUqXnoH07YTsdaUmn6pcitFU7hup2LagPWztDyhBoylBl4rO2LU1Zrh2UiwceKmMBGRFkImLfbvu/taXKcERdzuFgYwF9zLwDXXBRrly+QIlbi1oSszTfEElYmDZFIAPIkah84NoSGVYfTaE33dIiJnc79FofP3x7QnBmo3+xjCBYoPd9xJQTkYiQ3c9nwWSegcvWYmqNW1YbtdAcG741EKk+jcPcv2agAPwd21wEYPvnbcJ+/QVd5AC87vjw4XQX6qNCIGqecvQzo0Aglkumy6eblhvKT2DBxDJDnlK4dK0XQVcPega08UVYLFP/TjVXPcOM7ZLSgNlHVnioyTZMpq0r8yhH4OE0NhICmzTm/g4DraHNY+DasN4YHg/jJgiMXS/tU93LVw8C+kZXRhWKujdS9AjVzQ7RMUBngA0px+6I+6F7gD55qxTWmpI4rBhMBny7YCcsTtuV/2N6seyOQ2I0WGdV7Q605GVZ43AyvO6WPPpePTi0w6eGa2Lx81oF9nzG2YPlOKW1HDEws6eH9LO57CW4Da3jlSFqFcSX39laXEwBvxObQvjqPMy2lFkZgDRb5O/1kJHCtqTg0788wE2ZkGItXOse2uvjqrB3yusJJe1ZBDYRckBAcpYXPI
    PGADMIN_DEFAULT_PASSWORD: AgCLy+LP1LTM7lpOH12iQQg+eHr5Q5XYHOsGyKYZwxTHrjEQWMlyMdnUYr0hSBD2bJlWl/uajgu19LxzDTngQ8cNOBNV1FAQmJVwRmi+xN1giBdz4wpIg+pNQsUgzfKVbmSsHTSspTprWg+/AMdvAHZJYY1COzHyZpdOPQNhpm67FLhhUyJmW6InsWumN8nMjExWQ70nli4XN6FWV88ztwW/QAx7gP7LkUixNuIVH6/EsHN13Ph3WihXG/Lr1mhcekLwaNiT+Be1LRDW+edSenfAtaRey7jwWVYAWHM/qPr2CP6q2gFleKzu5+HzoaMsxRVD9yYb4dcug6kytpoEuLAFtjkgtf4M1nK8zg6QHCtI2OZ3JluWncTH300cBxYmb+7UechAfm2mMft6i5pZVwzYwvGxlF0Er6RNZDX+QTqnm+VwqGSHf17+l7cRwcqrQOs4TtbyF9dcivjFSU29RVtWUF0aVhLSSoKgF6RepMcVG3yQXkRxhfqew27VnRrC0PmG/EnaRE7yAkxmRj7ZPHsfvRT3uLk08gb/b3ELryKrOFB1oOVnPQ6S6MRC5lFG23dGTOqVl1JQs/Lkz1/gYXqlx/LnFm85/Zj0IQULSvJ1ple5HqDQyTtkQcyHTjxvM0hfLCIqcWoa6oSiYrbJFFwaJ6/vad0jzYzVb6Xai16LO8sLALlL60TH83G/3xgjIRK6RUsj/swmng==
  template:
    metadata:
      name: pgadmin-auth
      namespace: default
