---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    postgres-password: AgCSkB9aGPBre4GmW7p+1yzvl861r9tniZ2QA0hHEJAPolMxFc7chdVLgXZKFzBZxAWz1pVCJYUSqQFJ35BWOop0GIG+XgTOhXPeK123MAAlvEq32uwKfQMgF3yNi/WM7T0L+pumgj2eNYw9lzzT1FLd6TMK63lOeXy9sUSvHjTU/+RE2lBQGS4lsR1VhFX6yFFNOv3HEYjQYI5up2MKrKiAS46cV5IvlVPrwHQ9qZVCKdpEdBtWpmcArIvc4YzCQX2sINXrTfsn8HagfdRZefv+iSEJonQrAmAf0f9buu1R+ji6CC13STIkdXq7CX0f5fGUIhtCZjNqT7hwsmJng8i1HIOMCTrE0iT/SYkZfQ6EUVkWwZslgN7vCejNfuhSDDWDMT1fYy8E9T8n2le1WzZoW7Y6UAtiZHK8sccGDNGNffrbHFrbEqJZGufgR9PRwIKBcNtL46ON/M1dUJcogv2M+OLYEnOP91dL4AVR8AuHsd66Hmefd4mxsApU3PUGMGggmuiDFeh+ocesqCctFm25VfUMOTWFsxJEJ49ZvfL2motAAEUwKIvN+yS32LQTUcKM0VEA73CyTUlkNO5SfBnWdcKY01Hs93dQaT9bwwlQLiEIZanVbga6Jdp43zYi1C2wBoHPhXMi8YXm3W58iE6Zqvhy/qGFD0BiZUftauC57a50Vj+mValsPEtLx6jpy2VPbPPzfFA4OVAIrbfacc3IZeA=
  template:
    metadata:
      name: db-credentials
      namespace: default
