---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-auth
  namespace: mi-namespace
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgBymuBe7Po7qd0CSwwgQ0n7RK3T0sKacKI2xZq3Lo3xiy6fJzaJgrp6lJugukobQcWmwNKDCp58QX0JdCNyXEH/Tp5GDLmDXayMgcr5GSIFkFenR6PAIoSbC/9xL9m2BWpumtQ/YwnzaCKzUByecytJEnTYrHpTN49c2/pvPs2sBS1BN3LR9NUXXRhc7v7Js0qTHpJMEDvFARyU/6NZZKkXiRY9o1eYiaGzem7VjGQ1FXoB3QIUay6Ov3NOgi2J9vH2kkm/EgbcxiKAJ0NMTCwm2Jna0t3w9UtOccZUa4T50FXZL//nbUAbo+cIHBxZnjJvo3gC61fU9bnnGI+HrD+JtCCyOqJsHkBy4xpX2vCVrLtisX4m66GQRxilDrR9YrJmRmvvx5bw1fZi1FHwyPzjJyEF6j8Z/otKixDjd0F85JWh0VUUEsItSCj7wFv50bkcsPIkb7fQRPxG9GEPMAi0i/hw6dbiC/2/bTZwHFLjth4NVflkAYaPRvhQfk/efoNPi5i8VKipAkZWhlwiVYApgzIKu7yN44+uNFcfS2I9+4Xl+4lS7Zfd549u8wxB4iiFrqdry2XVVxMG9fCbErIMRY6M4KLytgbeQECGRJkZYHZNNRk0iLaIhRUHBVebY67oT0HHwpZYN2LCHLILQWG2pqpb7vzd4kAj6bpC+5JIq9EJXUcJm75+H0sdzM/dRRpwFYvl+gL6djuBihYq9plx1820
    PGADMIN_DEFAULT_PASSWORD: AgBT4WVLFuJ1I3rXdBH9ZO+sKiHWa39q3DHNoWC4OsqXto+l60CtXzq9pjmZG2ev1thJ4EEGPoWYTdmTg407uA2vOdUFhNup+m8jaM94iIaE4Ry6dTW1sFpRtyWM6dR5FhVGWqR6LUAJl8nSAW6Nb9KCaj4JnBTkYqcICPngXOpKdhmZ6XDTZdMCpt/LTUKT1tZLsq2wowQAt2dykwKHIHXWQeOSXM9x3YVSPA7pagGl9UH837faPpYLQyu7KidHHeVHqG3M0dphI4R7FHDEeY5CShgYe1SYU05HuV/I1TT7yszoY1s9lvDWuCWGFfx+l8c1HGevA1h8TNhx9h+KVaIwuGupGzYkcPP/3SWvYckXXE/lMzHBRPz/eLZE0SUyywzeEUQtNjYR5JtQ8JvAv05e1njb6tEQt4ZHn38opFwjSkMLwD+V3PUsi5ZZQPwDsfTB9+hXNrencN26tyA9jR9f3gP19WvyC61ePWyrB6b2UxUktWUlpbF6CH+lEq+qQZGmSsIQLkbJ/LKTJUdROYPjpRiJD4xBbzlNj93XktOYkAJfN+dDscjIM5MFWb0k5L6xCkOYUFt7jtxO+zAYUTwC20bLkMKXn0URWUVmKWjmF+bVYpQGYz7zPxasaa8mnVyvJW6XvRDoTU1BON0N3iofFN4lMSnE38whIbQxlhft7xfkLb5QzIgi3tnrObOgAX9+sPRNlHfYdA==
  template:
    metadata:
      name: pgadmin-auth
      namespace: mi-namespace
